- name: Install Docker Prereqs
  hosts: dev
  remote_user: jason
  gather_facts: yes
  tasks:
    - package:
        name: "{{item}}"
        state: latest
      with_items:
        - curl
    - apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        state: present

- name: Install Docker
  hosts: dev
  remote_user: jason
  gather_facts: yes
  handlers:
    - import_tasks: roles/handlers/main.yml
  tasks:
    - package:
        name: "docker-ce"
        state: latest
    - user: 
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes
      notify: restart docker

